# Usar una imagen base de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios
COPY simulador_partido.py .

# Comando para ejecutar la aplicación
CMD ["python", "simulador_partido.py"]
